"""Aggregate Mermaid classDiagram blocks into docs/UML_ALL.md."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATTERNS_DIR = ROOT / "patterns"
OUTPUT = ROOT / "docs" / "UML_ALL.md"


def _extract_diagram(path: Path) -> str | None:
    text = path.read_text(encoding="utf-8")
    match = re.search(
        r"类图 \(Mermaid\):\s*\n((?:    .+\n)+)",
        text,
    )
    if not match:
        return None
    lines = [ln.strip() for ln in match.group(1).strip().splitlines()]
    return "\n".join(lines)


def main() -> None:
    parts = [
        "# 23 Patterns — UML Class Diagrams",
        "",
        "> Generated by `scripts/generate_uml_page.py`. Paste blocks into https://mermaid.live",
        "",
    ]
    for path in sorted(PATTERNS_DIR.glob("[0-9][0-9]_*.py")):
        diagram = _extract_diagram(path)
        title = path.stem
        parts.append(f"## {title}")
        parts.append("")
        if diagram:
            parts.append("```mermaid")
            parts.append(diagram)
            parts.append("```")
        else:
            parts.append("_No diagram in docstring._")
        parts.append("")
    OUTPUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"[uml] wrote {OUTPUT}")


if __name__ == "__main__":
    main()
